// Types
export type {
  BilingualText,
  Locale,
  EntityType,
  Status,
  Visibility,
  ResultBlock,
  RunRecord,
  ReproducibilityInfo,
  EvalRecord,
  ActionItem,
  EdgeType,
  Edge,
  BaseEntity,
  ResearchProject,
  Publication,
  Experiment,
  Dataset,
  MLModel,
  CodeRepo,
  TechnicalNote,
  LitReview,
  MeetingLog,
  IdeaEntry,
  Skill,
  Method,
  MaterialSystem,
  Metric,
  Collaborator,
  Institution,
  MediaItem,
  Entity,
} from './types.js';

export { ENTITY_TYPES, EDGE_TYPES } from './types.js';

// Zod Schemas
export {
  bilingualTextSchema,
  localeSchema,
  entityTypeSchema,
  statusSchema,
  visibilitySchema,
  edgeTypeSchema,
  resultBlockSchema,
  runRecordSchema,
  reproducibilityInfoSchema,
  evalRecordSchema,
  actionItemSchema,
  edgeSchema,
  baseEntitySchema,
  researchProjectSchema,
  publicationSchema,
  experimentSchema,
  datasetSchema,
  mlModelSchema,
  codeRepoSchema,
  technicalNoteSchema,
  litReviewSchema,
  meetingLogSchema,
  ideaEntrySchema,
  skillSchema,
  methodSchema,
  materialSystemSchema,
  metricSchema,
  collaboratorSchema,
  institutionSchema,
  mediaItemSchema,
  schemaMap,
  entitySchema,
} from './schemas.js';

// Validation
export { validateEntity, validateEdge, validateAll } from './validate.js';
export type { ValidationResult } from './validate.js';
